# fly.toml app configuration file generated for dkvand on 2026-07-05T12:49:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dkvand'
primary_region = 'arn'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[vm]]
  memory = '768mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 768
  processes = ['app']
  size = 'shared-cpu-1x'
